### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by TheDiamondYT1** [PrimusLV/UltraFactions#3]
Why are you using arrays? Use SQLite - its much more efficient in my opinion. And its easier than having an array with over 300 names for big servers.
To make the database is easy

``` php
private $db

//OnEnable
$this->db = new \SQLite3($this->getDataFolder(), "UltraFactions.db");

//OnDisable
$this->db->close();
```

There is more to it than this, but this is the absolute basics.

**Comment by TheDiamondYT1** [comment]
And please, use a git client.

**Comment by PrimusLV** [comment]
In future i will be using DataProvider class providing 3 types of providers: yaml, SQLite3, MySQL.

**Comment by TheDiamondYT1** [comment]
Ewww yaml. #Gay

**Comment by Thunder33345** [comment]
Ewww discriminate against certain types of data provider
#EWWW

**Comment by PrimusLV** [comment]
Creating Data Providers!
