### ISSUE TITLE
No economy

### ISSUE THREAD

**Issue by daniktheboss** [PrimusLV/UltraFactions#9]
I use economy api and it doesn't work!

**Comment by devin5411** [comment]
Please give more Detail

**Comment by daniktheboss** [comment]
I have economy api and it says economy plugin not loaded... so after everything loads I do /reload and then it gets the plugin... but then it crashes... tell me if u need the error... I really want this plugin!

**Comment by daniktheboss** [comment]
Please fix!

**Comment by daniktheboss** [comment]
Yall so inactive! Plugin is going to a waste!

**Comment by PrimusLV** [comment]
I've closed this plugin forever. :(
